name: vinecopula

channels:
    - conda-forge
    - defaults

dependencies:
        - python=3.11
        - numpy
        - pandas
        - matplotlib
        - scipy
        - networkx
        - jupyter
        - nbsphinx
        - sphinx
        - sphinx-autoapi>=3.0
        - sphinx-rtd-theme